[workspace.package]
version = "0.0.1"
edition = "2024"

authors = ["Aldo Cortesi <aldo@corte.si>"]
description = "Anthropic Hooks for Rust"
license = "MIT"
repository = "https://github.com/tenxhq/code-hooks"
keywords = ["mcp", "anthropic", "claude"]

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.metadata.nanocode]
schema-version = 1
requires-nanocode = ">=0.1, <0.2"
features = "all"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false
