// @generated by `ruskel-snapshot`; do not edit.
//
// Package: code-hooks
// Publish: crates.io
// Workspace dependencies: claude-transcript
// Workspace dependents: hooktest, rust-hook

//! A Rust library for building hooks for Claude Code.
//!
//! Claude Code hooks are user-defined shell commands that execute at various
//! points in Claude Code's lifecycle. They provide deterministic control over
//! Claude Code's behavior, ensuring certain actions always happen rather than
//! relying on the LLM to choose to run them.
//!
//! This library implements the JSON-based hook protocol used by Claude Code
//! only, avoiding the less well-defined error code protocol. This means
//! code-hooks tools always exit with status code 0, and return well-formed JSON
//! responses.
//!
//! # Example
//!
//! ```rust,no_run
//! use code_hooks::{HookResponse, Input, PreToolUse, PreToolUseOutput, Result};
//!
//! fn main() -> Result<()> {
//!     let input = PreToolUse::read()?;
//!
//!     if input.tool_name == "Bash" {
//!         if let Some(command) = input.tool_input.get("command").and_then(|v| v.as_str()) {
//!             if command.contains("rm -rf") {
//!                 PreToolUseOutput::block("Dangerous command detected").respond();
//!             }
//!         }
//!     }
//!
//!     PreToolUseOutput::approve("Command validated").respond();
//! }
//! ```

use std::{
    collections::HashMap,
    fmt::{Debug, Display},
};

use claude_transcript::TranscriptEntry;
use serde::{de::Deserialize, ser::Serialize};
use serde_json::Value;

/// Trait for hook response types that can be serialized and sent to stdout.
///
/// This trait provides a standard way to respond from Claude Code hooks by:
/// 1. Serializing the response to JSON
/// 2. Printing it to stdout
/// 3. Exiting with status code 0
///
/// # Example
///
/// ```no_run
/// use code_hooks::{HookResponse, PreToolUseOutput};
///
/// let response = PreToolUseOutput::approve("Looks good");
/// response.respond(); // Prints JSON and exits
/// ```
// Not dyn-compatible.
pub trait HookResponse: Serialize {
    /// Serialize the response to JSON, print to stdout, and exit with status 0.
    fn respond(self) -> never
    where
        Self: Sized, {
    }
}

/// Trait for hook input types that can be read from stdin.
///
/// This trait provides a standard way to read hook inputs by:
/// 1. Reading all content from stdin
/// 2. Parsing it as JSON
/// 3. Deserializing to the appropriate type
///
/// # Example
///
/// ```rust,no_run
/// use code_hooks::{Input, PreToolUse};
///
/// let input = PreToolUse::read().expect("Failed to read input");
/// println!("Tool name: {}", input.tool_name);
/// ```
// Not dyn-compatible.
pub trait Input: Sized + for<'de> Deserialize<'de> {
    /// Read and parse input from stdin.
    fn read() -> crate::Result<Self> {}
}

/// Trait for hook input types that can read their associated transcript file.
///
/// This trait provides a standard way to read and parse the transcript file
/// referenced in the hook input's transcript_path field.
pub trait TranscriptReader {
    /// Read and parse the transcript file.
    ///
    /// Returns a vector of transcript entries from the JSONL file at
    /// transcript_path.
    fn read_transcript(&self) -> crate::Result<Vec<TranscriptEntry>>;
}

/// Decision type for approve/block operations.
///
/// Used in PreToolUse, PostToolUse, and Stop hooks to control execution flow.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Decision {
    /// Approve the operation (PreToolUse only - bypasses permission system)
    Approve,
    /// Block the operation and provide feedback to Claude
    Block,
}

/// Error types for hook operations
#[derive(Debug, Display, std::error::Error)]
pub enum Error {
    /// Error reading from stdin
    #[error("failed to read from stdin: {0}")]
    Io(std::io::Error),
    /// Error parsing JSON input
    #[error("failed to parse JSON: {0}")]
    JsonParse(serde_json::Error),
    /// Invalid exit code provided
    #[error("invalid exit code {0}: codes 0 and 2 are reserved")]
    InvalidExitCode(i32),
}

impl From<serde_json::Error> for Error {}

impl From<std::io::Error> for Error {}

/// Input structure for Notification hooks.
///
/// Notification hooks run when Claude Code sends notifications, allowing
/// you to customize how you receive alerts (e.g., when Claude needs input
/// or permission to run something).
#[derive(Debug, Deserialize<'de>, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct Notification {
    /// Unique identifier for the current Claude Code session
    pub session_id: String,
    /// Path to the conversation transcript JSON file
    pub transcript_path: String,
    /// The notification message content
    pub message: String,
    /// The notification title (typically "Claude Code")
    pub hook_event_name: String,
}

impl Notification {
    /// Create a response that allows normal notification handling
    ///
    /// The notification is displayed normally.
    pub fn passthrough() -> NotificationOutput;

    /// Create a response that stops Claude from continuing
    ///
    /// This prevents Claude from continuing after the notification.
    pub fn stop(&self, reason: &str) -> NotificationOutput;
}

impl Input for Notification {}

impl TranscriptReader for Notification {}

/// Output structure for Notification hooks.
///
/// Controls continuation and output visibility for notification handling.
#[derive(Debug, Default, Deserialize<'de>, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationOutput {
    /// Whether Claude should continue after hook execution (default: true)
    #[serde(rename = "continue", skip_serializing_if = "is_none")]
    pub continue_: Option<bool>,
    /// Message shown to user when continue is false
    #[serde(skip_serializing_if = "is_none")]
    pub stop_reason: Option<String>,
    /// Hide output from transcript mode (default: false)
    #[serde(skip_serializing_if = "is_none")]
    pub suppress_output: Option<bool>,
}

impl NotificationOutput {
    /// Set the continue field to false and provide a stop reason
    pub fn and_stop(self, reason: &str) -> Self;

    /// Set whether to suppress output in transcript mode
    pub fn and_suppress_output(self, suppress: bool) -> Self;
}

impl HookResponse for NotificationOutput {}

/// Input structure for PostToolUse hooks.
///
/// PostToolUse hooks run immediately after a tool completes successfully.
/// They can provide feedback to Claude but cannot prevent the tool from running
/// (since it already ran).
#[derive(Debug, Deserialize<'de>, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct PostToolUse {
    /// Unique identifier for the current Claude Code session
    pub session_id: String,
    /// Path to the conversation transcript JSON file
    pub transcript_path: String,
    /// Name of the tool that was called
    pub tool_name: String,
    /// Tool-specific input parameters that were used
    pub tool_input: HashMap<String, Value>,
    /// Tool-specific response data. The exact schema depends on the tool.
    pub tool_response: HashMap<String, Value>,
}

impl PostToolUse {
    /// Create a block response that suppresses the normal tool result
    ///
    /// Claude sees the reason as an error message instead of the actual tool
    /// output.
    pub fn block(&self, reason: &str) -> PostToolUseOutput;

    /// Create a passthrough response that sends the normal tool result to
    /// Claude
    ///
    /// The tool result is passed through unchanged. Any reason provided would
    /// be discarded.
    pub fn passthrough(&self) -> PostToolUseOutput;
}

impl Input for PostToolUse {}

impl TranscriptReader for PostToolUse {}

/// Output structure for PostToolUse hooks.
///
/// Provides feedback to Claude after a tool has already executed.
#[derive(Debug, Default, Deserialize<'de>, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PostToolUseOutput {
    /// Whether to provide feedback to Claude.
    /// - `Block`: Automatically prompts Claude with reason
    /// - `None`: No feedback provided
    ///
    /// Note: Cannot use `Approve` since the tool already ran
    #[serde(skip_serializing_if = "is_none")]
    pub decision: Option<Decision>,
    /// Feedback message for Claude (used when decision is Block)
    #[serde(skip_serializing_if = "is_none")]
    pub reason: Option<String>,
    /// Whether Claude should continue after hook execution (default: true)
    #[serde(rename = "continue", skip_serializing_if = "is_none")]
    pub continue_: Option<bool>,
    /// Message shown to user when continue is false
    #[serde(skip_serializing_if = "is_none")]
    pub stop_reason: Option<String>,
    /// Hide output from transcript mode (default: false)
    #[serde(skip_serializing_if = "is_none")]
    pub suppress_output: Option<bool>,
}

impl PostToolUseOutput {
    /// Set the continue field to false and provide a stop reason
    pub fn and_stop(self, reason: &str) -> Self;

    /// Set whether to suppress output in transcript mode
    pub fn and_suppress_output(self, suppress: bool) -> Self;

    /// Create a block response that suppresses the normal tool result
    ///
    /// Claude sees the reason as an error message instead of the actual tool
    /// output. The tool has already executed, but this replaces what Claude
    /// sees.
    pub fn block(reason: &str) -> Self;

    /// Create a passthrough response that sends the normal tool result to
    /// Claude
    ///
    /// This omits the decision field, so the normal tool_result is passed to
    /// Claude. Any reason provided would be discarded since there's no
    /// decision to attach it to.
    pub fn passthrough() -> Self;
}

impl HookResponse for PostToolUseOutput {}

/// Input structure for PreToolUse hooks.
///
/// PreToolUse hooks run after Claude creates tool parameters but before
/// processing the tool call. They can approve or block the operation.
#[derive(Debug, Deserialize<'de>, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct PreToolUse {
    /// Unique identifier for the current Claude Code session
    pub session_id: String,
    /// Path to the conversation transcript JSON file
    pub transcript_path: String,
    /// Name of the tool being called (e.g., "Bash", "Write", "Edit")
    pub tool_name: String,
    /// Tool-specific input parameters. The exact schema depends on the tool.
    pub tool_input: HashMap<String, Value>,
}

impl PreToolUse {
    /// Create an approval response that bypasses the permission system
    ///
    /// The tool executes immediately. The reason is shown to the user but not
    /// Claude.
    pub fn approve(&self, reason: &str) -> PreToolUseOutput;

    /// Create a block response that prevents tool execution
    ///
    /// The reason is passed to Claude as feedback.
    pub fn block(&self, reason: &str) -> PreToolUseOutput;

    /// Create a passthrough response that defers to Claude's regular approval
    /// flow
    ///
    /// The agent may show an approval dialogue or proceed based on its
    /// configuration.
    pub fn passthrough(&self) -> PreToolUseOutput;
}

impl Input for PreToolUse {}

impl TranscriptReader for PreToolUse {}

/// Output structure for PreToolUse hooks.
///
/// Controls whether a tool call proceeds and provides feedback to Claude.
#[derive(Debug, Default, Deserialize<'de>, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PreToolUseOutput {
    /// Whether to approve or block the tool call.
    /// - `Approve`: Bypasses the permission system, reason shown to user but
    ///   not Claude
    /// - `Block`: Prevents execution, reason shown to Claude
    /// - `None`: Follows existing permission flow
    #[serde(skip_serializing_if = "is_none")]
    pub decision: Option<Decision>,
    /// Explanation for the decision. Usage depends on decision type:
    /// - For `Approve`: Shown to user but not Claude
    /// - For `Block`: Shown to Claude as feedback
    /// - For `None`: Ignored
    #[serde(skip_serializing_if = "is_none")]
    pub reason: Option<String>,
    /// Whether Claude should continue after hook execution (default: true).
    /// If false, Claude stops processing. This is different from blocking
    /// a specific tool call.
    #[serde(rename = "continue", skip_serializing_if = "is_none")]
    pub continue_: Option<bool>,
    /// Message shown to user when continue is false. Not shown to Claude.
    #[serde(skip_serializing_if = "is_none")]
    pub stop_reason: Option<String>,
    /// Hide output from transcript mode (default: false)
    #[serde(skip_serializing_if = "is_none")]
    pub suppress_output: Option<bool>,
}

impl PreToolUseOutput {
    /// Set the continue field to false and provide a stop reason
    pub fn and_stop(self, reason: &str) -> Self;

    /// Set whether to suppress output in transcript mode
    pub fn and_suppress_output(self, suppress: bool) -> Self;

    /// Create an approval response that bypasses the permission system
    ///
    /// The tool executes immediately. The reason is shown to the user but not
    /// Claude.
    pub fn approve(reason: &str) -> Self;

    /// Create a block response that prevents tool execution
    ///
    /// The reason is passed to Claude as feedback.
    pub fn block(reason: &str) -> Self;

    /// Create a passthrough response that defers to Claude's regular approval
    /// flow
    ///
    /// This omits the decision field, allowing the agent to show an approval
    /// dialogue or proceed based on its configuration.
    pub fn passthrough() -> Self;
}

impl HookResponse for PreToolUseOutput {}

/// Type alias for Results in this library
pub type Result<T> = Result<T, Error>;

/// Input structure for Stop hooks.
///
/// Stop hooks run when Claude Code has finished responding. They can
/// block Claude from stopping and request continuation.
#[derive(Debug, Deserialize<'de>, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct Stop {
    /// Unique identifier for the current Claude Code session
    pub session_id: String,
    /// Path to the conversation transcript JSON file
    pub transcript_path: String,
    /// True when Claude Code is already continuing as a result of a stop hook.
    /// Check this to prevent infinite loops.
    pub stop_hook_active: bool,
}

impl Stop {
    /// Create a response that allows Claude to stop normally
    ///
    /// This is the default behavior when no decision is provided.
    pub fn allow(&self) -> StopOutput;

    /// Create a block response to prevent Claude from stopping
    ///
    /// Claude will continue processing with the provided reason.
    pub fn block(&self, reason: &str) -> StopOutput;

    /// Create a response that stops Claude immediately
    ///
    /// This prevents any further processing and shows the stop reason to the
    /// user.
    pub fn stop(&self, reason: &str) -> StopOutput;
}

impl Input for Stop {}

impl TranscriptReader for Stop {}

/// Output structure for Stop hooks.
///
/// Controls whether Claude can stop or must continue processing.
#[derive(Debug, Default, Deserialize<'de>, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StopOutput {
    /// Whether to block Claude from stopping.
    /// - `Block`: Prevents stopping, must provide reason
    /// - `None`: Allows Claude to stop normally
    #[serde(skip_serializing_if = "is_none")]
    pub decision: Option<Decision>,
    /// Required when decision is Block. Tells Claude how to proceed.
    #[serde(skip_serializing_if = "is_none")]
    pub reason: Option<String>,
    /// Whether Claude should continue after hook execution (default: true).
    /// Takes precedence over decision if set to false.
    #[serde(rename = "continue", skip_serializing_if = "is_none")]
    pub continue_: Option<bool>,
    /// Message shown to user when continue is false
    #[serde(skip_serializing_if = "is_none")]
    pub stop_reason: Option<String>,
    /// Hide output from transcript mode (default: false)
    #[serde(skip_serializing_if = "is_none")]
    pub suppress_output: Option<bool>,
}

impl StopOutput {
    /// Set the continue field to false and provide a stop reason
    pub fn and_stop(self, reason: &str) -> Self;

    /// Set whether to suppress output in transcript mode
    pub fn and_suppress_output(self, suppress: bool) -> Self;

    /// Create a block response to prevent Claude from stopping
    pub fn block(reason: &str) -> Self;
}

impl HookResponse for StopOutput {}

/// Input structure for SubagentStop hooks.
///
/// SubagentStop hooks run when a subagent has finished responding. They can
/// block the subagent from stopping and request continuation. This event has
/// exactly the same semantics as Stop but is only called for subagents.
#[derive(Debug, Deserialize<'de>, Serialize)]
#[serde(rename_all = "snake_case")]
pub struct SubagentStop {
    /// Unique identifier for the current Claude Code session
    pub session_id: String,
    /// Path to the conversation transcript JSON file
    pub transcript_path: String,
    /// True when the subagent is already continuing as a result of a
    /// SubagentStop hook. Check this to prevent infinite loops.
    pub stop_hook_active: bool,
}

impl SubagentStop {
    /// Create a response that allows the subagent to stop normally
    ///
    /// This is the default behavior when no decision is provided.
    pub fn allow(&self) -> SubagentStopOutput;

    /// Create a block response to prevent the subagent from stopping
    ///
    /// The subagent will continue processing with the provided reason.
    pub fn block(&self, reason: &str) -> SubagentStopOutput;

    /// Create a response that stops the subagent immediately
    ///
    /// This prevents any further processing and shows the stop reason to the
    /// user.
    pub fn stop(&self, reason: &str) -> SubagentStopOutput;
}

impl Input for SubagentStop {}

impl TranscriptReader for SubagentStop {}

/// Output structure for SubagentStop hooks.
///
/// Controls whether the subagent can stop or must continue processing.
#[derive(Debug, Default, Deserialize<'de>, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SubagentStopOutput {
    /// Whether to block the subagent from stopping.
    /// - `Block`: Prevents stopping, must provide reason
    /// - `None`: Allows the subagent to stop normally
    #[serde(skip_serializing_if = "is_none")]
    pub decision: Option<Decision>,
    /// Required when decision is Block. Tells the subagent how to proceed.
    #[serde(skip_serializing_if = "is_none")]
    pub reason: Option<String>,
    /// Whether the subagent should continue after hook execution (default:
    /// true). Takes precedence over decision if set to false.
    #[serde(rename = "continue", skip_serializing_if = "is_none")]
    pub continue_: Option<bool>,
    /// Message shown to user when continue is false
    #[serde(skip_serializing_if = "is_none")]
    pub stop_reason: Option<String>,
    /// Hide output from transcript mode (default: false)
    #[serde(skip_serializing_if = "is_none")]
    pub suppress_output: Option<bool>,
}

impl SubagentStopOutput {
    /// Set the continue field to false and provide a stop reason
    pub fn and_stop(self, reason: &str) -> Self;

    /// Set whether to suppress output in transcript mode
    pub fn and_suppress_output(self, suppress: bool) -> Self;

    /// Create a block response to prevent the subagent from stopping
    pub fn block(reason: &str) -> Self;
}

impl HookResponse for SubagentStopOutput {}
