// @generated by `ruskel-snapshot`; do not edit.
//
// Package: rust-hook
// Publish: crates.io
// Binaries: rust-hook
// Workspace dependencies: claude-transcript, code-hooks
// Workspace dependents: none

/// Find the nearest ancestor directory containing a `Cargo.toml` file.
/// Returns the directory path as a `String`.
pub fn find_project_root(file_path: &str) -> String;

/// Determine whether the provided path refers to a Rust source file.
pub fn is_rust_file(file_path: &str) -> bool;

pub mod utils {
    pub use crate::{find_project_root, is_rust_file};
}
